run:
  concurrency: 4
  timeout: 30s
linters-settings:
  lll:
    line-length: 100
  gocognit:
    min-complexity: 45
  gocritic:
    disabled-checks:
      - commentFormatting
linters:
  enable-all: true
  disable:
    - wsl
    - gochecknoglobals
    - goimports
    - goerr113
    - gochecknoinits
    - gofumpt
    - noctx
    - nlreturn
    - gci
    - funlen
    - goconst
    - gomnd
    - dupl
    - exhaustivestruct
    - wrapcheck
    - errorlint
    - gosec
