run:
  concurrency: 4
  timeout: 30s
linters-settings:
  funlen:
    lines: 70
    statements: 60
linters:
  enable-all: true
  disable:
    - wsl
    - gochecknoglobals
    - goimports
    - goerr113
    - testpackage
