run:
  concurrency: 4
  timeout: 30s
linters-settings:
  lll:
    line-length: 100
linters:
  enable-all: true
  disable:
    - wsl
    - gochecknoglobals
    - goimports
    - goerr113
    - gochecknoinits
    - gofumpt
    - noctx
    - nlreturn
    - gci
    - funlen
    - goconst
    - gomnd
    - dupl
