version: '3.7'
services:
  database:
    image: postgis/postgis:12-master
    container_name: rampart-database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rampart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    image: rampart-backend
  migrations:
    image: rampart-backend
    container_name: rampart-migrations
    volumes:
      - .:/go/src/app
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/migrations
  mining:
    image: rampart-backend
    container_name: rampart-mining
    volumes:
      - .:/go/src/app
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/mining -once -miner domria-primary
  mining-domria-primary:
    image: rampart-backend
    container_name: rampart-mining-domria-primary
    volumes:
      - .:/go/src/app
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/mining -miner domria-primary
    ports:
      - 9001:9001
    restart: on-failure
  mining-domria-secondary:
    image: rampart-backend
    container_name: rampart-mining-domria-secondary
    volumes:
      - .:/go/src/app
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/mining -miner domria-secondary
    ports:
      - 9002:9002
    restart: on-failure
  checks:
    build:
      context: .
      dockerfile: docker/checks.dockerfile
    image: rampart-checks
  gofmt:
    image: rampart-checks
    container_name: rampart-gofmt
    volumes:
      - .:/go/src/app
    command: gofmt -w -s .
  lint:
    image: rampart-checks
    container_name: rampart-lint
    volumes:
      - .:/go/src/app
    command: golangci-lint run
  test:
    image: rampart-checks
    container_name: rampart-test
    volumes:
      - .:/go/src/app
    command: richgo test github.com/xXxRisingTidexXx/rampart/internal/mining/domria
  notebook:
    build:
      context: .
      dockerfile: docker/notebook.dockerfile
    image: rampart-notebook
  jupyter:
    image: rampart-notebook
    container_name: rampart-jupyter
    volumes:
      - ./notebooks:/home/jovyan
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
volumes:
  database:
    name: rampart-database
networks:
  default:
    name: rampart-default
