version: '3.8'
x-migrate: &x-migrate
  image: migrate/migrate:v4.12.2
  volumes:
    - ./migrations:/migrations
  env_file:
    - .env
x-messis: &x-messis
  image: rampart-messis
  volumes:
    - ./go.mod:/go/src/app/go.mod
    - ./go.sum:/go/src/app/go.sum
    - ./cmd:/go/src/app/cmd
    - ./internal:/go/src/app/internal
    - ./config:/go/src/app/config
    - ./scientific:/go/src/app/scientific
    - ./images:/go/src/app/images
  env_file:
    - .env
x-gochecks: &x-gochecks
  image: rampart-gochecks
  volumes:
    - ./go.mod:/go/src/app/go.mod
    - ./go.sum:/go/src/app/go.sum
    - ./.golangci.yml:/go/src/app/.golangci.yml
    - ./cmd:/go/src/app/cmd
    - ./internal:/go/src/app/internal
    - ./config:/go/src/app/config
  env_file:
    - .env
x-twinkle: &x-twinkle
  image: rampart-twinkle
  volumes:
    - ./requirements:/app/requirements
    - ./rampart:/app/rampart
    - ./templates:/app/templates
    - ./scientific:/app/scientific
    - ./config:/app/config
  env_file:
    - .env
x-auge: &x-auge
  image: rampart-auge
  entrypoint: python -m rampart.auge
  volumes:
    - ./requirements:/app/requirements
    - ./rampart:/app/rampart
    - ./scientific:/app/scientific
    - ./config:/app/config
  env_file:
    - .env
  ipc: host
x-pychecks: &x-pychecks
  image: rampart-pychecks
  volumes:
    - ./tox.ini:/app/tox.ini
    - ./requirements:/app/requirements
    - ./rampart:/app/rampart
    - ./templates:/app/templates
    - ./config:/app/config
  env_file:
    - .env
services:
  database:
    image: postgis/postgis:13-3.0-alpine
    container_name: rampart-database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rampart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
  migrate:
    <<: *x-migrate
    container_name: rampart-migrate
    command: -path migrations -database $RAMPART_DATABASE_DSN up
  generate:
    <<: *x-migrate
    container_name: rampart-generate
  messis:
    <<: *x-messis
    build:
      context: .
      dockerfile: docker/messis.dockerfile
    container_name: rampart-messis
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/messis -debug -miner domria-primary
  warhol:
    <<: *x-messis
    container_name: rampart-warhol
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/warhol
  travesty:
    <<: *x-messis
    container_name: rampart-travesty
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/travesty
  gochecks:
    build:
      context: .
      dockerfile: docker/gochecks.dockerfile
    image: rampart-gochecks
  lint:
    <<: *x-gochecks
    container_name: rampart-lint
    command: golangci-lint run
  test:
    <<: *x-gochecks
    container_name: rampart-test
    command:
      - richgo
      - test
      - github.com/xXxRisingTidexXx/rampart/internal/domria
      - github.com/xXxRisingTidexXx/rampart/internal/metrics
  notebook:
    build:
      context: .
      dockerfile: docker/notebook.dockerfile
    image: rampart-notebook
    container_name: rampart-notebook
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./images:/home/jovyan/images
      - ./scientific:/home/jovyan/scientific
      - ./.cache:/home/jovyan/.cache
      - ./.config:/home/jovyan/.config
      - ./.ipython:/home/jovyan/.ipython
      - ./.jupyter:/home/jovyan/.jupyter
      - ./.local:/home/jovyan/.local
      - ./.npm:/home/jovyan/.npm
    ports:
      - 8888:8888
    env_file:
      - .env
  twinkle:
    <<: *x-twinkle
    build:
      context: .
      dockerfile: docker/twinkle.dockerfile
    container_name: rampart-twinkle
    command: python -m rampart.twinkle
    ports:
      - 9211:9211
  coquus:
    <<: *x-twinkle
    container_name: rampart-coquus
    command: python -m rampart.coquus
  auge:
    <<: *x-auge
    build:
      context: .
      dockerfile: docker/auge.dockerfile
    container_name: rampart-auge
    command: -debug
  pychecks:
    build:
      context: .
      dockerfile: docker/pychecks.dockerfile
    image: rampart-pychecks
  flake8:
    <<: *x-pychecks
    container_name: rampart-flake8
    command: flake8 --config=tox.ini .
  mypy:
    <<: *x-pychecks
    container_name: rampart-mypy
    command: mypy --ignore-missing-imports rampart
  pytest:
    <<: *x-pychecks
    container_name: rampart-pytest
    command: pytest -vv rampart --full-trace -p no:cacheprovider
  messis-domria-primary:
    <<: *x-messis
    container_name: rampart-messis-domria-primary
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/messis -miner domria-primary
    ports:
      - 9001:9001
  messis-domria-secondary:
    <<: *x-messis
    container_name: rampart-messis-domria-secondary
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/messis -miner domria-secondary
    ports:
      - 9002:9002
  auge-cron:
    <<: *x-auge
    container_name: rampart-auge-cron
    ports:
      - 9003:9003
volumes:
  database:
    name: rampart-database
networks:
  default:
    name: rampart-default
