version: '3.7'
services:
  database:
    image: postgis/postgis:12-master
    container_name: rampart-database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rampart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
  checks:
    build:
      context: .
      dockerfile: docker/checks.dockerfile
    image: rampart-checks
  lint:
    image: rampart-checks
    container_name: rampart-lint
    volumes:
      - .:/go/src/app
    command: golangci-lint run
volumes:
  database:
    name: rampart-database
networks:
  default:
    name: rampart-default
