version: '3.7'
x-migrate: &x-migrate
  image: migrate/migrate:v4.12.2
  volumes:
    - ./migrations:/migrations
  env_file:
    - .env
x-aggregation: &x-aggregation
  image: rampart-aggregation
  volumes:
    - ''
  env_file:
    - .env
x-checks: &x-checks
  image: rampart-checks
  volumes:
    - .:/go/src/app
x-ranking: &x-ranking
  image: rampart-ranking
  volumes:
    - ''
  env_file:
    - .env
x-recognition: &x-recognition
  image: rampart-recognition
  volumes:
    - ''
  env_file:
    - .env
services:
  database:
    image: postgis/postgis:12-master
    container_name: rampart-database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rampart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
  migrate:
    <<: *x-migrate
    container_name: rampart-migrate
    command: -path migrations -database $RAMPART_DATABASE_DSN up
  generate:
    <<: *x-migrate
    container_name: rampart-generate
  aggregation:
    build:
      context: .
      dockerfile: docker/aggregation.dockerfile
    image: rampart-aggregation
  mining:
    <<: *x-aggregation
    container_name: rampart-mining
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/mining -debug -miner domria-primary
  mining-domria-primary:
    <<: *x-aggregation
    container_name: rampart-mining-domria-primary
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/mining -miner domria-primary
    ports:
      - 9001:9001
  mining-domria-secondary:
    <<: *x-aggregation
    container_name: rampart-mining-domria-secondary
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/mining -miner domria-secondary
    ports:
      - 9002:9002
  checks:
    build:
      context: .
      dockerfile: docker/checks.dockerfile
    image: rampart-checks
  lint:
    <<: *x-checks
    container_name: rampart-lint
    command: golangci-lint run
  test:
    <<: *x-checks
    container_name: rampart-test
    command:
      - richgo
      - test
      - github.com/xXxRisingTidexXx/rampart/internal/domria
      - github.com/xXxRisingTidexXx/rampart/internal/metrics
  notebook:
    build:
      context: .
      dockerfile: docker/notebook.dockerfile
    image: rampart-notebook
    container_name: rampart-notebook
    volumes:
      - .:/home/jovyan
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    env_file:
      - .env
  ranking:
    build:
      context: .
      dockerfile: docker/ranking.dockerfile
    image: rampart-ranking
  telebot:
    <<: *x-ranking
    container_name: rampart-telebot
    command: python -m rampart.telebot
  browsing:
    <<: *x-ranking
    container_name: rampart-browsing
    command: python -m rampart.browsing
    ports:
      - 9211:9211
  recognition:
    build:
      context: .
      dockerfile: docker/recognition.dockerfile
    image: rampart-recognition
volumes:
  database:
    name: rampart-database
networks:
  default:
    name: rampart-default
