version: '3.8'
x-migrate: &x-migrate
  image: migrate/migrate:v4.12.2
  volumes:
    - ./migrations:/migrations
  env_file:
    - .env
x-golang: &x-golang
  image: rampart-golang
  volumes:
    - ./go.mod:/go/src/app/go.mod
    - ./go.sum:/go/src/app/go.sum
    - ./cmd:/go/src/app/cmd
    - ./internal:/go/src/app/internal
    - ./config:/go/src/app/config
    - ./scientific:/go/src/app/scientific
    - ./images:/go/src/app/images
    - ./templates:/go/src/app/templates
  env_file:
    - .env
x-python: &x-python
  image: rampart-python
  volumes:
    - ./requirements:/app/requirements
    - ./rampart:/app/rampart
    - ./scientific:/app/scientific
    - ./config:/app/config
  env_file:
    - .env
  ipc: host
services:
  database:
    image: postgis/postgis:13-3.0-alpine
    container_name: rampart-database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rampart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
  migrate:
    <<: *x-migrate
    container_name: rampart-migrate
    command: -path migrations -database $RAMPART_DATABASE_DSN up
  generate:
    <<: *x-migrate
    container_name: rampart-generate
  golang:
    build:
      context: .
      dockerfile: docker/golang.dockerfile
    image: rampart-golang
  messis:
    <<: *x-golang
    container_name: rampart-messis
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/messis
    ports:
      - 9001:9001
  miner:
    <<: *x-golang
    container_name: rampart-miner
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/messis -miner domria
  warhol:
    <<: *x-golang
    container_name: rampart-warhol
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/warhol
  travesty:
    <<: *x-golang
    container_name: rampart-travesty
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/travesty
  assistant:
    <<: *x-golang
    container_name: rampart-assistant
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/assistant
    ports:
      - 9002:9002
  publisher:
    <<: *x-golang
    container_name: rampart-publisher
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/assistant -publisher
  moderator:
    <<: *x-golang
    container_name: rampart-moderator
    command: go run github.com/xXxRisingTidexXx/rampart/cmd/moderator
  notebook:
    build:
      context: .
      dockerfile: docker/notebook.dockerfile
    image: rampart-notebook
    container_name: rampart-notebook
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./images:/home/jovyan/images
      - ./scientific:/home/jovyan/scientific
      - ./.cache:/home/jovyan/.cache
      - ./.config:/home/jovyan/.config
      - ./.ipython:/home/jovyan/.ipython
      - ./.jupyter:/home/jovyan/.jupyter
      - ./.local:/home/jovyan/.local
      - ./.npm:/home/jovyan/.npm
    ports:
      - 8888:8888
    env_file:
      - .env
  python:
    build:
      context: .
      dockerfile: docker/python.dockerfile
    image: rampart-python
  twinkle-debug:
    <<: *x-python
    container_name: rampart-twinkle-debug
    command: python -m rampart.twinkle -debug
  coquus:
    <<: *x-python
    container_name: rampart-coquus
    command: python -m rampart.coquus
  auge-debug:
    <<: *x-python
    container_name: rampart-auge-debug
    command: python -m rampart.auge -debug
  auge:
    <<: *x-python
    container_name: rampart-auge
    command: python -m rampart.auge
    ports:
      - 9003:9003
  twinkle:
    <<: *x-python
    container_name: rampart-twinkle
    command: python -m rampart.twinkle
    ports:
      - 9004:9004
volumes:
  database:
    name: rampart-database
networks:
  default:
    name: rampart-default
