dsnParams: &dsnParams
  sslmode: disable
  binary_parameters: yes
userAgent: &userAgent rampart-mining-bot/1.0.0
srid: &srid 4326
mining:
  dsnParams:
    <<: *dsnParams
    connect_timeout: '10'
  gatherer:
    failedFetchingTracker:
      name: rampart_failed_fetching
      help: Total number of failed flat fetching attempts
      labels:
        - miner
    fetchingDurationTracker:
      name: rampart_fetching_duration
      help: Total elapsed time of a single flat API call in seconds
      buckets:
        - 0.1
        - 0.5
        - 1
        - 1.5
        - 2
        - 5
        - 10
      labels:
        - miner
    fetchedFlatsTracker:
      name: rampart_fetched_flats
      help: Total amount of fetched flats
      labels:
        - miner
    locatedFlatsTracker:
      name: rampart_located_flats
      help: Total amount of flats with accurate geo coordinates
      labels:
        - miner
    unlocatedFlatsTracker:
      name: rampart_unlocated_flats
      help: Total quantity of flats without distinct points and addresses
      labels:
        - miner
    failedGeocodingTracker:
      name: rampart_failed_geocoding
      help: Total amount of flats whose Nominatim search yielded HTTP errors
      labels:
        - miner
    emptyGeocodingTracker:
      name: rampart_empty_geocoding
      help: Total amount of flats whose Nominatim search yielded no responses
      labels:
        - miner
    successfulGeocodingTracker:
      name: rampart_successful_geocoding
      help: Total amount of flats whose Nominatim search yielded coordinates
      labels:
        - miner
    geocodingDurationTracker:
      name: rampart_geocoding_duration
      help: Total elapsed time of a single Nominatim API call in seconds
      buckets:
        - 0.5
        - 1
        - 1.5
        - 2
        - 5
      labels:
        - miner
    validatedFlatsTracker:
      name: rampart_validated_flats
      help: Total quantity of valid flats
      labels:
        - miner
    invalidatedFlatsTracker:
      name: rampart_invalidated_flats
      help: Total amount of invalid flats
      labels:
        - miner
    createdFlatsTracker:
      name: rampart_created_flats
      help: Total count of inserted to the DB flats
      labels:
        - miner
    updatedFlatsTracker:
      name: rampart_updated_flats
      help: Total count of modified flats
      labels:
        - miner
    unalteredFlatsTracker:
      name: rampart_unaltered_flats
      help: Total count of flats without content changes
      labels:
        - miner
    failedStoringTracker:
      name: rampart_failed_storing
      help: Total quantity of failed flat storing transactions
      labels:
        - miner
    readingDurationTracker:
      name: rampart_reading_duration
      help: Total elapsed time of a single flat SQL reading in seconds
      buckets:
        - 0.001
        - 0.005
        - 0.01
        - 0.05
        - 0.1
        - 0.5
        - 1
      labels:
        - miner
    creationDurationTracker:
      name: rampart_creation_duration
      help: Total elapsed time of a single flat SQL insertion in seconds
      buckets:
        - 0.005
        - 0.01
        - 0.1
        - 0.5
        - 1
      labels:
        - miner
    updateDurationTracker:
      name: rampart_update_duration
      help: Total elapsed time of a single flat SQL mutation in seconds
      buckets:
        - 0.005
        - 0.01
        - 0.1
        - 0.5
        - 1
      labels:
        - miner
    miningDurationTracker:
      name: rampart_mining_duration
      help: Total elapsed time of a single miner execution in seconds
      buckets:
        - 1
        - 2
        - 4
        - 10
        - 15
        - 30
        - 60
      labels:
        - miner
  server:
    readTimeout: 5s
    writeTimeout: 5s
    maxHeaderBytes: 1048576
  miners:
    domria: &domria
      fetcher:
        timeout: 30s
        portion: 100
        flags:
          primary: newbuildings=1
          secondary: secondary=1
        headers:
          User-Agent: *userAgent
        searchURL: https://dom.ria.com/searchEngine/?category=1&realty_type=2&operation_type=1&fullCategoryOperation=1_2_1&%s&page=%d&limit=%d
        srid: *srid
      sanitizer:
        originURLPrefix: https://dom.ria.com/uk/
        imageURLPrefix: https://cdn.riastatic.com/photos/
        stateEnding: ька
        stateSuffix: ' область'
        districtEnding: ий
        districtSuffix: ' район'
      geocoder:
        timeout: 5s
        headers:
          User-Agent: *userAgent
        statelessCities:
          - Київ
        searchURL: https://nominatim.openstreetmap.org/search?state=%s&city=%s&county=%s&street=%s+%s&format=json&countrycodes=ua
        srid: *srid
      validator:
        minPrice: 1
        minTotalArea: 12
        maxTotalArea: 560
        minLivingArea: 0
        minKitchenArea: 0
        minRoomNumber: 1
        maxRoomNumber: 9
        minSpecificArea: 12
        maxSpecificArea: 130
        minFloor: 1
        minTotalFloor: 2
        maxTotalFloor: 50
        minLongitude: -180
        maxLongitude: 180
        minLatitude: -90
        maxLatitude: 90
      storer:
        updateTiming: 168h
    domriaPrimary:
      <<: *domria
      alias: domria-primary
      housing: primary
      spec: '@every 2m'
      port: 9001
    domriaSecondary:
      <<: *domria
      alias: domria-secondary
      housing: secondary
      spec: '@every 2m'
      port: 9002
migrations:
  dsnParams:
    <<: *dsnParams
    connect_timeout: '15'
