dsnParams: &dsnParams
  sslmode: disable
  binary_parameters: yes
userAgent: &userAgent rampart-mining-bot/1.0.0
srid: &srid 4326
mining:
  dsnParams:
    <<: *dsnParams
    connect_timeout: '10'
  gatherer:
    runTracker:
      name: rampart_mining_run_total
      help: Total number of a certain job executions
      labels:
        - miner
        - status
    statuses:
      success: success
      failure: failure
    geocodingTracker:
      name: rampart_mining_geocoding_total
      help: Total amount of flats passed through the Nominatim geocoder
      labels:
        - miner
        - category
    categories:
      located: located
      unlocated: unlocated
      failed: failed
      inconclusive: inconclusive
      successful: successful
    validationTracker:
      name: rampart_mining_validation_total
      help: Total amount of flats checked by validator
      labels:
        - miner
        - verdict
    verdicts:
      valid: valid
      invalid: invalid
    storingTracker:
      name: rampart_mining_storing_total
      help: Total amount of flats affected the DB state
      labels:
        - miner
        - consequence
    consequences:
      created: created
      updated: updated
      unaltered: unaltered
      failed: failed
    durationTracker:
      name: rampart_mining_duration_seconds
      help: Timing of a certain I/O-bound task execution
      buckets:
        - 0.001
        - 0.01
        - 0.1
        - 0.5
        - 1
        - 2
        - 5
        - 10
        - 30
      labels:
        - miner
        - process
    processes:
      fetching: fetching
      geocoding: geocoding
      reading: reading
      creation: creation
      update: update
      run: run
  server:
    readTimeout: 5s
    writeTimeout: 5s
    maxHeaderBytes: 1048576
  miners:
    domria: &domria
      fetcher:
        timeout: 30s
        portion: 100
        flags:
          primary: newbuildings=1
          secondary: secondary=1
        headers:
          User-Agent: *userAgent
        searchURL: https://dom.ria.com/searchEngine/?category=1&realty_type=2&operation_type=1&fullCategoryOperation=1_2_1&%s&page=%d&limit=%d
        srid: *srid
      sanitizer:
        originURLPrefix: https://dom.ria.com/uk/
        imageURLPrefix: https://cdn.riastatic.com/photos/
        stateEnding: ька
        stateSuffix: ' область'
        districtEnding: ий
        districtSuffix: ' район'
      geocoder:
        timeout: 5s
        headers:
          User-Agent: *userAgent
        statelessCities:
          - Київ
        searchURL: https://nominatim.openstreetmap.org/search?state=%s&city=%s&county=%s&street=%s+%s&format=json&countrycodes=ua
        srid: *srid
      validator:
        minPrice: 1
        minTotalArea: 12
        maxTotalArea: 560
        minLivingArea: 0
        minKitchenArea: 0
        minRoomNumber: 1
        maxRoomNumber: 9
        minSpecificArea: 12
        maxSpecificArea: 130
        minFloor: 1
        minTotalFloor: 2
        maxTotalFloor: 50
        minLongitude: -180
        maxLongitude: 180
        minLatitude: -90
        maxLatitude: 90
    domriaPrimary:
      <<: *domria
      alias: domria-primary
      housing: primary
      spec: '@every 30s'
      port: 9001
    domriaSecondary:
      <<: *domria
      alias: domria-secondary
      housing: secondary
      spec: '@every 30s'
      port: 9002
migrations:
  dsnParams:
    <<: *dsnParams
    connect_timeout: '15'
